<?php


class BreadCrumbControl extends WebControl {

	var $m_trail = array();
	var $m_headerTemplate;
	var $m_betweenTemplate;
	var $m_itemTemplate = '%s';
	var $m_footerTemplate;

	var $m_siteMapFile; // Not implemented, in the future this will allow this control to be generated by a file
	
	function prepareContent() {
		
		$elements = array();
		foreach($this->m_trail as $element) {
			$text = $element->getTitle();
			$link = $element->getLink();
			
			$text = '<span class="breadcrumb-element">' . $text . '</span>';
			
			if (!empty($link)) $text = '<a href="' . substr(ConfigurationManager::get('DIR_WS_HOME'), 0, -1) . $element->getLink() . '" class="breadcrumb-link">' . $text . '</a>';
			
			$elements[] = sprintf($this->m_itemTemplate, $text);
		}

		$this->setRenderedContent($this->getHeaderTemplate() . implode($this->getBetweenTemplate(), $elements) . $this->getFooterTemplate());
	}
	function addCrumb($title, $link=null) {
		$this->m_trail[] = new BreadCrumbElement($title, $link);
	}
	
	function getHeaderTemplate() { return $this->m_headerTemplate; }
	function getBetweenTemplate() { return $this->m_betweenTemplate; }
	function getFooterTemplate() { return $this->m_footerTemplate; }

	function setHeaderTemplate($template) { $this->m_headerTemplate = $template; }
	function setBetweenTemplate($template) { $this->m_betweenTemplate = $template; }
	function setFooterTemplate($template) { $this->m_footerTemplate = $template; }
}
?>